baseurl = "https://mszczeblewski.github.io/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 0
  fullWidthTheme = false
  centerTheme = true
  favicon = "favicon.png"
[languages]
  [languages.en]
    title = "MSzczeblewski"
    subtitle = "A place to cronicle my tech journey"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read More"

    [languages.en.params.logo]
      logoText = "MSzczeblewski"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
#      [[languages.en.menu.main]]
#        identifier = "showcase"
#        name = "Showcase"
#        url = "/showcase"
 [taxonomies]
  category = 'categories'
  tag = 'tags'
